---
- name: Deploy pipeline metrics {{ env }} instance
  hosts: pipeline-metrics-{{ env }}
  vars_files:
    - ../vaults/{{ env }}/secret-vars.yaml
  roles:
    - pipeline-metrics
  environment:
    K8S_AUTH_API_KEY: '{{ ocp_token }}'
    K8S_AUTH_HOST: '{{ ocp_host }}'
