---
kind: DeploymentConfig
apiVersion: v1
metadata:
  labels:
    app: "{{ pipeline_metrics_name }}"
    env: "{{ env }}"
    suffix: "{{ suffix }}"
  name: "{{ pipeline_metrics_name }}-{{ suffix }}"
spec:
  replicas: {{ pipeline_metrics_name_replicas | int }}  # yamllint disable-line rule:braces
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 3600
  template:
    metadata:
      labels:
        app: "{{ pipeline_metrics_name }}"
        env: "{{ env }}"
        suffix: "{{ suffix }}"
      name: "{{ pipeline_metrics_name }}-{{ suffix }}"
    spec:
      containers:
        - name: "{{ pipeline_metrics_name }}"
          image: "{{ pipeline_metrics_image_pull_spec }}"
          ports:
            - containerPort: {{ pipeline_metrics_name_port | int }}  # yamllint disable-line rule:braces
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: {{ pipeline_metrics_name_port | int }}  # yamllint disable-line rule:braces
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ pipeline_metrics_name_port | int }}  # yamllint disable-line rule:braces
            initialDelaySeconds: 15
            timeoutSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 256Mi
