---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ pipeline_metrics_cookie_secret_name }}"
  labels:
    app: "{{ pipeline_metrics_name }}"
    env: "{{ env }}"
    suffix: "{{ suffix }}"
type: Opaque
stringData:
  cookie-secret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
