---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: "{{ pipeline_metrics_name }}"
    env: "{{ env }}"
    suffix: "{{ suffix }}"
  name: "operator-repos-{{ suffix }}"
data:
  repos.yml: |
    {{ pipeline_metrics_operator_repos | to_json }}
