---
kind: Secret
apiVersion: v1
metadata:
  labels:
    app: "{{ pipeline_metrics_name }}"
    env: "{{ env }}"
    suffix: "{{ suffix }}"
  name: "operator-repos-{{ suffix }}"
data:
  repos.yml: "{{ pipeline_metrics_operator_repos | b64encode }}"
  # This technically creates a secret containing a JSON file
  # but YAML fully supports JSON
