---
kind: DeploymentConfig
apiVersion: v1
metadata:
  labels:
    app: "{{ pipeline_metrics_name }}"
    env: "{{ env }}"
    suffix: "{{ suffix }}"
  name: "{{ pipeline_metrics_name }}-{{ suffix }}"
spec:
  replicas: {{ pipeline_metrics_name_replicas | int }}  # yamllint disable-line rule:braces
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 3600
  template:
    metadata:
      labels:
        app: "{{ pipeline_metrics_name }}"
        env: "{{ env }}"
        suffix: "{{ suffix }}"
      name: "{{ pipeline_metrics_name }}-{{ suffix }}"
    spec:
      serviceAccountName: "{{ service_account_name }}"
      volumes:
        - name: operator-repos-config
          configMap:
            name: "operator-repos-{{ suffix }}"
        - name: proxy-tls
          secret:
            secretName: "{{ pipeline_metrics_tls_secret_name }}"
        - name: cookie-secret
          secret:
            secretName: "{{ pipeline_metrics_cookie_secret_name }}"
      containers:
        - name: "{{ pipeline_metrics_name }}"
          image: "{{ pipeline_metrics_image_pull_spec }}"
          ports:
            - containerPort: {{ pipeline_metrics_name_port | int }}  # yamllint disable-line rule:braces
              protocol: TCP
          volumeMounts:
            - name: operator-repos-config
              mountPath: /etc/metrics-conf/
              readOnly: true
          env:
            - name: METRICS_OPERATOR_REPOS_CFG_PATH
              value: /etc/metrics-conf/repos.yml
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: {{ pipeline_metrics_name_port | int }}  # yamllint disable-line rule:braces
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ pipeline_metrics_name_port | int }}  # yamllint disable-line rule:braces
            initialDelaySeconds: 15
            timeoutSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
        - name: oauth-proxy
          image: "{{ pipeline_metrics_oauth_proxy_image }}"
          ports:
            - containerPort: {{ pipeline_metrics_oauth_proxy_port | int }}  # yamllint disable-line rule:braces
              name: https
              protocol: TCP
          args:
            - --https-address=:{{ pipeline_metrics_oauth_proxy_port }}
            - --provider=openshift
            - --openshift-service-account={{ service_account_name }}
            - --upstream=http://localhost:{{ pipeline_metrics_name_port }}
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret-file=/etc/oauth-cookie/cookie-secret
            - --redirect-url=https://{{ pipeline_metrics_name_url }}/oauth/callback
            - --skip-provider-button
            - --pass-basic-auth=false
          volumeMounts:
            - name: proxy-tls
              mountPath: /etc/tls/private
              readOnly: true
            - name: cookie-secret
              mountPath: /etc/oauth-cookie
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
