---
name: Build

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows:
      - validation
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@3a51aade9afa17e5c78256bcbe2e1ee08c7b995b  # v3.0.2
        with:
          image: pipeline-metrics
          tags: latest ${{ github.sha }}
          dockerfiles: |
            ./Dockerfile

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37  # v3.0.0
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/redhat-isv
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
