---
name: Deployment

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows:
      - Build
    branches:
      - ISV-1691
    types:
      - completed
  # push:
  #   branches:
  #     - ISV-1691
  workflow_dispatch:

jobs:
  deploy-nonprod:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    environment:
      name: nonprod
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          echo "$SHORT_SHA"
          pip install --user openshift
      - name: Deploy nonprod environment
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/deploy.yaml
          directory: ./ansible
          requirements: playbooks/requirements.yaml
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --inventory inventory/pipeline-metrics
            --extra-vars "env=nonprod pipeline_metrics_image_tag=${{ github.sha }} suffix=${{ github.sha }}"
            --verbose

  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    needs:
      - deploy-nonprod
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip install --user openshift
      - name: Deploy nonprod environment
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/deploy.yaml
          directory: ./ansible
          requirements: playbooks/requirements.yaml
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --inventory inventory/pipeline-metrics
            --extra-vars "env=prod pipeline_metrics_image_tag=${{ github.sha }} suffix=${{ github.sha }}"
            --verbose

  release:
    name: Github release
    runs-on: ubuntu-latest
    needs:
      - deploy-prod
    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: quay.io

      - name: Tag image with a release tag
        run: |

          podman pull quay.io/redhat-isv/pipeline-metrics:${{ github.sha }}

          podman tag quay.io/redhat-isv/pipeline-metrics:${{ github.sha }} quay.io/redhat-isv/pipeline-metrics:released
          podman tag quay.io/redhat-isv/pipeline-metrics:${{ github.sha }} quay.io/redhat-isv/pipeline-metrics:${{ steps.tag_version.outputs.new_tag }}

          podman push quay.io/redhat-isv/pipeline-metrics:released
          podman push quay.io/redhat-isv/pipeline-metrics:${{ steps.tag_version.outputs.new_tag }}
