---
name: validation

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tox:
    name: Run unit tests and linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fedora-python/tox-github-action@v39.0
        with:
          tox_env: mypy,black,pylint,yamllint,bandit,pip-audit
          dnf_install: krb5-devel
