---
name: validation

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - ISV-1691
  workflow_dispatch:

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3

  tox:
    name: Run unit tests and linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fedora-python/tox-github-action@v0.4
        with:
          tox_env: mypy,black,pylint,yamllint,bandit,safety
