---
name: validation

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - ISV-1691
  workflow_dispatch:

jobs:
  tox:
    name: Run unit tests and linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fedora-python/tox-github-action@v37.0
        with:
          tox_env: mypy,black,pylint,yamllint,bandit,safety
